### PR TITLE
Rework/collision

### PR DESCRIPTION
**Pull request by Juyas**
- Rework collision mechanics for non-bullet collisions
- Remove old AABB and other collision related classes
- Support forces which can be added limitless to an dynamic object (RigidBody)
- Optimizations for component update cycle - less object transform requests and inconsistencies - transform position has a buffer now, to prevent inconsistencies in future patches
- Collider, Shapes and PhysicalEntity are seperately defined to be able to add more custom definitions in the future 
- Character Controller is NOT a final implementation - probably that's something that the engine should not implement out of the box, since controlling a character can be done in a lot of different ways

### CODE REVIEW

**Comment by Juyas** [comment]
This will receive its unit tests, after PR #41 is done and merged, since it contains require testing adjustments for all future tests.

**Comment by Juyas** [comment]
Added a couple of tests. Pls look over them and give feedback.

**Comment by athaun** [comment]
> Added a couple of tests. Pls look over them and give feedback.

Working on this, it may take some time.

**Comment by Juyas** [comment]
> > Added a couple of tests. Pls look over them and give feedback.
> 
> Working on this, it may take some time.

No problem, take your time, we can even do some tests together and you can ask some questions :)

**Comment by athaun** [comment]
This error is thrown on collision with the tilemap in DemoPlatformer.java (any further attempts to launch the window fail immediately with this same error.)
```
Exception in thread "main" java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lorg.joml.Vector2f; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lorg.joml.Vector2f; is in unnamed module of loader 'app')
	at physics.collision.CollisionUtil.expandingPolytopeAlgorithm(CollisionUtil.java:149)
	at physics.collision.Collisions$2.accept(Collisions.java:58)
	at physics.collision.Collisions$2.accept(Collisions.java:54)
	at ecs.StaticCollider.handleCollision(StaticCollider.java:157)
	at ecs.RigidBody.handleCollision(RigidBody.java:221)
	at scene.Scene.checkCollision(Scene.java:105)
	at scene.Scene.checkCollision(Scene.java:94)
	at ecs.GameObject.update(GameObject.java:128)
	at scene.Scene.updateGameObjects(Scene.java:204)
	at scene.SceneManager.updateGameObjects(SceneManager.java:128)
	at graphics.Window.showWindow(Window.java:168)
	at util.Engine.showWindow(Engine.java:62)
	at scenes.DemoPlatformer.main(DemoPlatformer.java:26)
```

**Comment by athaun** [comment]
I am also unable to run the DemoTopDown scene due to a concurrent modification error, probably a bug with the scene manager #31 
```
> Task :DemoTopDown.main() FAILED
called
called
called
called
called
Exception in thread "main" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at ecs.GameObject.start(GameObject.java:111)
	at scene.Scene.startGameObjects(Scene.java:133)
	at scene.SceneManager.enable(SceneManager.java:48)
	at graphics.Window.showWindow(Window.java:155)
	at util.Engine.showWindow(Engine.java:62)
	at scenes.DemoTopDown.main(DemoTopDown.java:25)
```

**Comment by Juyas** [comment]
Files have been edited, you should not encounter problems or error now - if so, pls provide more data, since I cannot reproduce some of them

**Comment by athaun** [comment]
> This error is thrown on collision with the tilemap in DemoPlatformer.java (any further attempts to launch the window fail immediately with this same error.)
> 
> ```
> Exception in thread "main" java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lorg.joml.Vector2f; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lorg.joml.Vector2f; is in unnamed module of loader 'app')
> 	at physics.collision.CollisionUtil.expandingPolytopeAlgorithm(CollisionUtil.java:149)
> 	at physics.collision.Collisions$2.accept(Collisions.java:58)
> 	at physics.collision.Collisions$2.accept(Collisions.java:54)
> 	at ecs.StaticCollider.handleCollision(StaticCollider.java:157)
> 	at ecs.RigidBody.handleCollision(RigidBody.java:221)
> 	at scene.Scene.checkCollision(Scene.java:105)
> 	at scene.Scene.checkCollision(Scene.java:94)
> 	at ecs.GameObject.update(GameObject.java:128)
> 	at scene.Scene.updateGameObjects(Scene.java:204)
> 	at scene.SceneManager.updateGameObjects(SceneManager.java:128)
> 	at graphics.Window.showWindow(Window.java:168)
> 	at util.Engine.showWindow(Engine.java:62)
> 	at scenes.DemoPlatformer.main(DemoPlatformer.java:26)
> ```
> 
>  2021-07-23.20-03-31.mp4

this bug is fixed in my last commit, however we should probably look deeper into the problem as you suggested on discord.

**Pull request merged**
