### PR TITLE
Feature/parsing

### PR DESCRIPTION
**Pull request by Juyas**
+ add a general purpose parsing structure
+ add a basic xml parser

### CODE REVIEW

**Review by athaun — COMMENTED** [review]
This looks good. I would like voxel to also take a look since it is rather dense so two sets of eyes are better than one.

**Review by PixelRifts — APPROVED** [review]
Wow a full on parser. Looks good

**Comment by Juyas** [comment]
> Wow a full on parser. Looks good

It does even have a structure to make a parser for a different file format more quickly :)

**Comment by Juyas** [comment]
Gonna add some DataObjectModel for conversion of different fileformats and java objects

**Review by PixelRifts — APPROVED** [review]

**Pull request merged**
