### PR TITLE
Bug Fixes in Audio Engine

### PR DESCRIPTION
**Pull request by HilbertCurve**
There were two bugs detected in the audio engine that crashed the whole game engine:
- playing audio files that were shorter than 64 kilobytes in quick succession would trick the engine into thinking it wasn't playing any audio, and hence break the audio buffering queue system
- OOB exception with playing short audio files

Thanks to @goldspark for spotting the issue.

### CODE REVIEW

**Comment by goldspark** [comment]
Merge this pls

**Comment by HilbertCurve** [comment]
While it's a bug that the whole engine should crash when this occurs, the AudioListener singleton should only be applied to one GameObject; generally that's the player character or some other sentinel entity.
Attempting to apply it multiple times will only shift the AudioListener to the latest GameObject it's applied to, or at least it should; instead it freaks out OpenAL because applying the listener to two different objects is an Invalid Operation.

**Comment by goldspark** [comment]
Idea, make the audio listener load with the engine .

**Comment by HilbertCurve** [comment]
Hmm that makes sense. Come to think of it, I'm not sure if the audio listener should even be a component; it'd be better if it was just positioned to the camera's location. We see through the camera, so I guess we should hear through it as well.

**Comment by goldspark** [comment]
I did apply Audio Listener to only one game object and it crashes this is what I get:

[FATAL] {audio.AudioMaster.alGetError(AudioMaster.java:99)} AL error received: Invalid Operation
[CRASH] {scenes.ezpacegame.EzSpaceDemo.main(EzSpaceDemo.java:70) -> audio.AudioMaster.alGetError(AudioMaster.java:100)} null
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "util.LoggingThread.log(String, int)" because "util.Log.loggingThread" is null
	at util.Log.crash(Log.java:279)
	at util.Engine.showWindow(Engine.java:79)
	at scenes.ezpacegame.EzSpaceDemo.main(EzSpaceDemo.java:70)

**Comment by HilbertCurve** [comment]
As of the most recent commit you can no longer attach the AudioListener to game objects; it seemed like an unnecessary function that wouldn't get much use. Instead it just positions itself at the camera's location.

**Comment by goldspark** [comment]
Still issue:

```
[FATAL] {audio.AudioMaster.alGetError(AudioMaster.java:103)} AL error received: Invalid Operation
[CRASH] {scenes.ezpacegame.EzSpaceDemo.main(EzAsteroidsDemo.java:70) -> audio.AudioMaster.alGetError(AudioMaster.java:104)} null
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "util.LoggingThread.log(String, int)" because "util.Log.loggingThread" is null
	at util.Log.crash(Log.java:279)
	at util.Engine.showWindow(Engine.java:79)
```

**Pull request merged**
